{"uid":"d9d6c18078018573","name":"User can add a Collection with the same name as a deleted Collection -- @1.1 ","fullName":"Collections: User can add a Collection with the same name as a deleted Collection","historyId":"a34d535ff7756f44d3753d91bfe6b623","time":{"start":1667412558912,"stop":1667412572022,"duration":13110},"status":"failed","statusMessage":"AssertionError\n","statusTrace":"  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/collection_steps.py\", line 176, in step_impl\n    assert message_element.text != error_message\n","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"AssertionError\n","statusTrace":"  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/collection_steps.py\", line 176, in step_impl\n    assert message_element.text != error_message\n","steps":[{"name":"Given User is logged in as username: technical_assignment, password: uhqom-duqmum-tepXe7","time":{"start":1667412558913,"stop":1667412570737,"duration":11824},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When User adds a Collection with title: Test Collection","time":{"start":1667412570737,"stop":1667412571481,"duration":744},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"Then Error: You already have a collection with that title., does not appear","time":{"start":1667412571481,"stop":1667412572022,"duration":541},"status":"failed","statusMessage":"AssertionError\n","statusTrace":"  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/collection_steps.py\", line 176, in step_impl\n    assert message_element.text != error_message\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true}],"attachments":[],"parameters":[],"stepsCount":3,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":true},"afterStages":[],"labels":[{"name":"severity","value":"normal"},{"name":"feature","value":"Collections"},{"name":"framework","value":"behave"},{"name":"language","value":"cpython3"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"error_message","value":"You already have a collection with that title."},{"name":"password","value":"uhqom-duqmum-tepXe7"},{"name":"title","value":"Test Collection"},{"name":"username","value":"technical_assignment"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"d9d6c18078018573.json","parameterValues":["You already have a collection with that title.","uhqom-duqmum-tepXe7","Test Collection","technical_assignment"]}