{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Product defects","children":[{"name":"AssertionError\n","children":[{"name":"User can add a Collection with the same name as a deleted Collection -- @1.1 ","uid":"5b331b2425eba50d","parentUid":"a730cf0b0a23aabea6d11aa0391c8a76","status":"failed","time":{"start":1667421344238,"stop":1667421357430,"duration":13192},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":["You already have a collection with that title.","uhqom-duqmum-tepXe7","Test Collection","technical_assignment"]}],"uid":"a730cf0b0a23aabea6d11aa0391c8a76"},{"name":"AssertionError: FAILED SUB-STEP: Given User is on the Home page\nSubstep info: Traceback (most recent call last):\n  File \"steps/login_steps.py\", line 17, in step_impl\n    wait_for_element_visibility(context, page_title_xpath)\n  File \"/home/runner/work/cinc_assignment/cinc_assignment/features/utils.py\", line 5, in wait_for_element_visibility\n    context.wait.until(expected_conditions.visibility_of_element_located((By.XPATH, element_xpath)))\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py\", line 90, in until\n    raise TimeoutException(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x559984f202c3 <unknown>\n#1 0x559984d2983a <unknown>\n#2 0x559984d62985 <unknown>\n#3 0x559984d62b61 <unknown>\n#4 0x559984d9ad14 <unknown>\n#5 0x559984d80f6d <unknown>\n#6 0x559984d98a50 <unknown>\n#7 0x559984d80d63 <unknown>\n#8 0x559984d557e3 <unknown>\n#9 0x559984d56a21 <unknown>\n#10 0x559984f6e18e <unknown>\n#11 0x559984f71622 <unknown>\n#12 0x559984f54aae <unknown>\n#13 0x559984f722a3 <unknown>\n#14 0x559984f48ecf <unknown>\n#15 0x559984f92588 <unknown>\n#16 0x559984f92706 <unknown>\n#17 0x559984fac8b2 <unknown>\n#18 0x7f1de6a7d609 <unknown>\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 26, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div[1]/div/nav/ul/li[4]/div/ul/li[6]/a\"}\n  (Session info: headless chrome=106.0.5249.119)\nStacktrace:\n#0 0x559984f202c3 <unknown>\n#1 0x559984d2983a <unknown>\n#2 0x559984d62985 <unknown>\n#3 0x559984d62b61 <unknown>\n#4 0x559984d9ad14 <unknown>\n#5 0x559984d80f6d <unknown>\n#6 0x559984d98a50 <unknown>\n#7 0x559984d80d63 <unknown>\n#8 0x559984d557e3 <unknown>\n#9 0x559984d56a21 <unknown>\n#10 0x559984f6e18e <unknown>\n#11 0x559984f71622 <unknown>\n#12 0x559984f54aae <unknown>\n#13 0x559984f722a3 <unknown>\n#14 0x559984f48ecf <unknown>\n#15 0x559984f92588 <unknown>\n#16 0x559984f92706 <unknown>\n#17 0x559984fac8b2 <unknown>\n#18 0x7f1de6a7d609 <unknown>\n\n\nTraceback (of failed substep):\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/runner/.local/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/login_steps.py\", line 26, in step_impl\n    log_out = context.driver.find_element(By.XPATH, log_out_xpath)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 856, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n\n","children":[{"name":"Recipe adjustment -- @1.1 ","uid":"6c7030ed0291f146","parentUid":"b8bcf21e72f8b729f2e32f479d6abc1f","status":"failed","time":{"start":1667421367802,"stop":1667421378168,"duration":10366},"flaky":true,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":["uhqom-duqmum-tepXe7","technical_assignment"]}],"uid":"b8bcf21e72f8b729f2e32f479d6abc1f"}],"uid":"8fb3a91ba5aaf9de24cc8a92edc82b5d"},{"name":"Test defects","children":[{"name":"selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div[1]/div/nav/ul/li[4]/div/ul/li[6]/a\"}\n  (Session info: headless chrome=106.0.5249.119)\nStacktrace:\n#0 0x559984f202c3 <unknown>\n#1 0x559984d2983a <unknown>\n#2 0x559984d62985 <unknown>\n#3 0x559984d62b61 <unknown>\n#4 0x559984d9ad14 <unknown>\n#5 0x559984d80f6d <unknown>\n#6 0x559984d98a50 <unknown>\n#7 0x559984d80d63 <unknown>\n#8 0x559984d557e3 <unknown>\n#9 0x559984d56a21 <unknown>\n#10 0x559984f6e18e <unknown>\n#11 0x559984f71622 <unknown>\n#12 0x559984f54aae <unknown>\n#13 0x559984f722a3 <unknown>\n#14 0x559984f48ecf <unknown>\n#15 0x559984f92588 <unknown>\n#16 0x559984f92706 <unknown>\n#17 0x559984fac8b2 <unknown>\n#18 0x7f1de6a7d609 <unknown>\n\n","children":[{"name":"Login -- @1.1 ","uid":"8d45c7ce4ef42664","parentUid":"c93e4bae054cc9f892d57ce8d309a7ce","status":"broken","time":{"start":1667421357431,"stop":1667421367801,"duration":10370},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":true,"retriesCount":0,"retriesStatusChange":false,"parameters":["uhqom-duqmum-tepXe7","technical_assignment"]}],"uid":"c93e4bae054cc9f892d57ce8d309a7ce"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}